apiVersion: v1
kind: ConfigMap
metadata:
  name: sk009-fluentd-config
  namespace: skala3-ai1
  labels:
    app: sk009-fastapi-ml-serving
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/fluentd/app.log.pos
      tag sk009-fastapi-ml-serving
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter sk009-fastapi-ml-serving>
      @type record_transformer
      <record>
        namespace  "#{ENV['MY_POD_NAMESPACE']}"
        pod_name   "#{ENV['MY_POD_NAME']}"
        app        sk009-fastapi-ml-serving
      </record>
    </filter>

    <match sk009-fastapi-ml-serving>
      @type stdout
    </match>

    # 운영 환경: 아래처럼 Elasticsearch / S3 / CloudWatch 등으로 맞게 추후 교체하기
    # <match sk009-fastapi-ml-serving>
    #   @type elasticsearch
    #   host elasticsearch.logging.svc.cluster.local
    #   port 9200
    #   index_name sk009-fastapi-ml-serving
    # </match>