apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk009-fluentd-log-pvc
  namespace: skala3-ai1
  labels:
    app: sk009-fastapi-ml-serving
spec:
  accessModes:
    - ReadWriteOnce        # EBS는 단일 Pod만 마운트 가능
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi